language: node_js
node_js:
  - "8"

cache: yarn

env:
  - NODE_ENV: test

services:
  - redis-server

branches:
  only:
  - develop
  - master
  - /^greenkeeper/.*$/

before_install:
  - yarn global add serverless greenkeeper-lockfile@1 apollo

install:
  - yarn

before_script:
  - greenkeeper-lockfile-update
  - yarn test:coverage
  - yarn
  - yarn start&

script:
  # - apollo schema:check --endpoint=http://localhost:1337/

after_script:
  - greenkeeper-lockfile-upload

deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: yarn deploy:dev
    on:
      node: "8"
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script:
      - yarn deploy:prod
      # - apollo schema:publish --endpoint=http://localhost:1337/
    on:
      node: "8"
      branch: master
