enum Languages {
  Any
  English
  Spanish
  French
  German
  Italian
  Portuguese
  Japanese
  Korean
  Russian
  SimplifiedChinese
  TraditionalChinese
  Hebrew
  Latin
  AncientGreek
  Arabic
  Sanskrit
  Phyrexian
}
