enum Subtypes {
  # Artifact Types
  Clue
  Contraption
  Equipment
  Fortification
  Treasure
  Vehicle

  # Creature Types
  Advisor
  Aetherborn
  Ally
  Angel
  Antelope
  Ape
  Archer
  Archon
  Artificer
  Assassin
  AssemblyWorker
  Atog
  Aurochs
  Avatar
  Azra
  Badger
  Barbarian
  Basilisk
  Bat
  Bear
  Beast
  Beeble
  Berserker
  Bird
  Blinkmoth
  Boar
  Bringer
  Brushwagg
  Camarid
  Camel
  Caribou
  Carrier
  Cat
  Centaur
  Cephalid
  Chimera
  Citizen
  Cleric
  Cockatrice
  Construct
  Coward
  Crab
  Crocodile
  Cyclops
  Dauthi
  Demon
  Deserter
  Devil
  Dinosaur
  Djinn
  Dragon
  Drake
  Dreadnought
  Drone
  Druid
  Dryad
  Dwarf
  Efreet
  Egg
  Elder
  Eldrazi
  Elemental
  Elephant
  Elf
  Elk
  Eye
  Faerie
  Ferret
  Fish
  Flagbearer
  Fox
  Frog
  Fungus
  Gargoyle
  Germ
  Giant
  Gnome
  Goat
  Goblin
  God
  Golem
  Gorgon
  Graveborn
  Gremlin
  Griffin
  Hag
  Harpy
  Head
  Hellion
  Hippo
  Hippogriff
  Homarid
  Homunculus
  Hornet
  Horror
  Horse
  Hound
  Human
  Hydra
  Hyena
  Illusion
  Imp
  Incarnation
  Insect
  Jackal
  Jellyfish
  Juggernaut
  Kavu
  Kirin
  Kithkin
  Knight
  Kobold
  Kor
  Kraken
  Lamia
  Lammasu
  Leech
  Leviathan
  Lhurgoyf
  Licid
  Lizard
  Manticore
  Masticore
  Mercenary
  Merfolk
  Metathran
  Minion
  Minotaur
  Mole
  Monger
  Mongoose
  Monk
  Monkey
  Moonfolk
  Mutant
  Myr
  Mystic
  Naga
  Nautilus
  Nephilim
  Nightmare
  Nightstalker
  Ninja
  Noggle
  Nomad
  Nymph
  Octopus
  Ogre
  Ooze
  Orb
  Orc
  Orgg
  Ouphe
  Ox
  Oyster
  Pangolin
  Pegasus
  Pentavite
  Pest
  Phelddagrif
  Phoenix
  Pilot
  Pincher
  Pirate
  Plant
  Praetor
  Prism
  Processor
  Rabbit
  Rat
  Rebel
  Reveler
  Rhino
  Rigger
  Rogue
  Rukh
  Sable
  Salamander
  Samurai
  Sand
  Saproling
  Satyr
  Scarecrow
  Scion
  Scorpion
  Scout
  Serf
  Serpent
  Servo
  Shade
  Shaman
  Shapeshifter
  Sheep
  Siren
  Skeleton
  Slith
  Sliver
  Slug
  Snake
  Soldier
  Soltari
  Spawn
  Specter
  Spellshaper
  Sphinx
  Spider
  Spike
  Spirit
  Splinter
  Sponge
  Squid
  Squirrel
  Starfish
  Surrakar
  Survivor
  Tetravite
  Thalakos
  Thopter
  Thrull
  Treefolk
  Trilobite
  Triskelavite
  Troll
  Turtle
  Unicorn
  Vampire
  Vedalken
  Viashino
  Volver
  Wall
  Warrior
  Wasp
  Weird
  Werewolf
  Whale
  Wizard
  Wolf
  Wolverine
  Wombat
  Worm
  Wraith
  Wurm
  Yeti
  Zombie
  Zubera

  # Enchantment Types
  Aura
  Cartouche
  Curse
  Saga
  Shrine

  # Land Types
  Desert
  Forest
  Gate
  Island
  Lair
  Locus
  Mine
  Mountain
  Plains
  PowerPlant
  Swamp
  Tower
  Urzas

  # Planeswalker Types
  Ajani
  Aminatou
  Angrath
  Arlinn
  Ashiok
  Bolas
  Chandra
  Dack
  Daretti
  Domri
  Dovin
  Dungeon
  Elspeth
  Estrid
  Freyalise
  Garruk
  Gideon
  Huatli
  Jace
  Jaya
  Karn
  Kaya
  Kiora
  Koth
  Liliana
  Master
  Nahiri
  Narset
  Nissa
  Nixilis
  Ral
  Rowan
  Saheeli
  Samut
  Sarkhan
  Sorin
  Tamiyo
  Teferi
  Tezzeret
  Tibalt
  Ugin
  Urza
  Venser
  Vivien
  Vraska
  Will
  Windgrace
  Xenagos
  Yanggu
  Yanling

  # Spell Types
  Arcane
  Trap
}
