enum Watermarks {
  abzan
  agentsofsneak
  arena
  atarka
  azorius
  boros
  colorpie
  conspiracy
  crossbreedlabs
  dungeonsanddragons
  dci
  dengekimaoh
  dimir
  dromoka
  flavor
  fnm
  goblinexplosioneers
  golgari
  grandprix
  gruul
  herospath
  izzet
  japanjunior
  jeskai
  junior
  juniorapac
  junioreurope
  kolaghan
  leagueofdastardlydoom
  mardu
  mirran
  mps
  mtg
  mtg10
  mtg15
  nerf
  ojutai
  orderofthewidget
  orzhov
  phyrexian
  planeswalker
  protour
  rakdos
  scholarship
  selesnya
  set
  silumgar
  simic
  sultai
  temur
  transformers
  wotc
  wpn
}
